services:
  mysql:
    image: mysql:8.0
    container_name: mysql_performance_test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: performance_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - perf_test_network
    command: --default-authentication-plugin=mysql_native_password
    
  # Pre-compiled Percona with RocksDB support
  percona:
    build:
      context: ./percona-custom
      dockerfile: Dockerfile
    container_name: percona_performance_test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: performance_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - percona_data:/var/lib/mysql
      - ./config/percona.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - perf_test_network
    command: --default-authentication-plugin=mysql_native_password
    
  mariadb:
    image: mariadb:latest
    container_name: mariadb_performance_test
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: performance_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - perf_test_network
    
  # Sysbench testing container
  sysbench:
    image: severalnines/sysbench:latest
    container_name: sysbench_tester
    depends_on:
      - mysql
      - percona
      - mariadb
    volumes:
      - ./scripts:/scripts:ro
      - ./performance_reports:/reports
    networks:
      - perf_test_network
    command: sleep infinity
    
  # Monitoring and metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitor
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - perf_test_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # MySQL exporter for MySQL metrics
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "testuser:testpass@(mysql:3306)/performance_test"
    depends_on:
      - mysql
    networks:
      - perf_test_network

  # MySQL exporter for Percona metrics  
  percona-exporter:
    image: prom/mysqld-exporter:latest
    container_name: percona_exporter
    ports:
      - "9105:9104"
    environment:
      DATA_SOURCE_NAME: "testuser:testpass@(percona:3306)/performance_test"
    depends_on:
      - percona
    networks:
      - perf_test_network
      
  # MySQL exporter for MariaDB metrics  
  mariadb-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mariadb_exporter
    ports:
      - "9106:9104"
    environment:
      DATA_SOURCE_NAME: "testuser:testpass@(mariadb:3306)/performance_test"
    depends_on:
      - mariadb
    networks:
      - perf_test_network
      
  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - perf_test_network

volumes:
  mysql_data:
  percona_data:
  mariadb_data:
  prometheus_data:
  grafana_data:

networks:
  perf_test_network:
    driver: bridge