global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'percona-exporter'
    static_configs:
      - targets: ['percona-exporter:9104']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'mariadb-exporter'
    static_configs:
      - targets: ['mariadb-exporter:9104']
    scrape_interval: 5s
    metrics_path: /metrics